version: "3"
networks:
  app-tier:
    driver: bridge
services:
  memgraph-mage:
    build: ./memgraph
    entrypoint:
      [
        "/usr/lib/memgraph/memgraph",
        "--telemetry-enabled=false",
        "--log-level=WARNING",
      ]
    ports:
      - "7687:7687"
      - "7444:7444"
    networks:
      - app-tier
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0  --reload
    ports:
      - 8000:8000
    depends_on:
      - memgraph-mage
    networks:
      - app-tier
    environment: 
      - MG_HOST=memgraph-mage
      - MG_PORT=7687
      - BEARER_TOKEN=${BEARER_TOKEN}
      - TWITTER_RULES=${TWITTER_RULES}
    env_file:
      - .env
  frontend-app:
    container_name: frontend-app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-tier
